package: markdowneditor
version: '1.0.0'
author: KLXM Crossmedia
supportpage: https://github.com/KLXM/markdowneditor/issues

page:
    title: 'translate:markdowneditor_title'
    perm: admin
    subpages:
        profiles:
            title: 'translate:markdowneditor_profiles'
        demo:
            title: 'translate:markdowneditor_demo'
        settings:
            title: 'translate:markdowneditor_settings'
        help:
            title: 'translate:markdowneditor_help'
            subPath: README.md

requires:
    redaxo: '^5.13'
    php: '>=8.1'

installer_ignore:
    - node_modules
    - .github
    - scripts
